version: "3"
services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - portfolio

  react-app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.react
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  portfolio:
    driver: bridge

volumes:
  jenkins_home:
